### ISSUE TITLE
A similar tool with YaST Font module

### ISSUE THREAD

**Issue by guoyunhe** [yast/yast-fonts#15]
I am a member of openSUSE Chinese community. Last week I made a small fontconfig front-end for customizing font effects. Someone told me that YaST is planning to release a new module of similar functions.

Here is what I have done: https://github.com/guoyunhe/font-config-master

This tool modifies user configuration (~/.config/fontconfig/fonts.conf), while YaST usually modifies global configuration in /etc/

What features will be included in YaST Font module?

**Comment by pgajdos** [comment]
Best way to figure out is to try the module ;).
