### ISSUE TITLE
"Installed families..." hangs 1 core at 100% for seconds

### ISSUE THREAD

**Issue by avemilia** [yast/yast-fonts#46]
When choosing fonts to override, pressing "Installed families..." hangs 1 core at 100% for 30+ seconds. It happens every time the button is pressed. I assume this is due to the lack of caching.

**Comment by dgdavid** [comment]
Hi!

In a virtual machine with 3 cores and 4GB of RAM, and openSUSE TW installed, it took to me just 2 seconds after pressing that button.

According to the `fc-list | wc -l` output, the system has 1366 available fonts.

Could you provide more details?

Thanks.

**Comment by avemilia** [comment]
Unfortunately, I no longer possess that particular hardware and I don't use OpenSUSE anymore. Feel free to close.

**Comment by dgdavid** [comment]
Sad to read that. I hope you can give another try to openSUSE in the future :)

Thank you so much for your report and feedback.
